# Generated by Django 5.2 on 2025-05-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0003_extractedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
                ('positions', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='document.extractedtext')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='indexer.term')),
            ],
            options={
                'unique_together': {('term', 'document')},
            },
        ),
    ]
